name: Deploy to Google Cloud Run - Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up Firebase Admin Credentials
        run: |
          echo '${{ secrets.FIREBASE_ADMIN_SERVICE_ACCOUNT }}' > ./.credentials/firebase-admin.json

      - name: Create credentials directory
        run: mkdir -p ./.credentials

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build --build-arg MODE=stage \
          -f Dockerfile \
          -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo:${{ github.sha }}

      - name: Deploy to Google Cloud Run - Production
        run: |
          TAG="${{ github.ref_name }}"
          gcloud run deploy todo-prod \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo:${{ github.sha }} \
            --tag $TAG \
            --platform managed \
            --no-traffic \
            --region asia-northeast1 \
            --allow-unauthenticated